# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachLab', '0006_auto_20180710_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='clientpackages/')),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('publish_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_datetime'],
            },
        ),
    ]
