# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachLab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
