# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachLab', '0004_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['star_count']},
        ),
        migrations.AddField(
            model_name='model',
            name='star_count',
            field=models.IntegerField(default=0),
        ),
    ]
