# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachLab', '0005_auto_20180709_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['-star_count']},
        ),
        migrations.AddField(
            model_name='model',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
